Repository kiransbaliga/System-Software-and-Microprocessors-Lab, pull requests merged in 2022-10, with the labels that each got.

#1 Updated code in Pg4pagereplacement.c
  SS/page replacement/Pg4pagereplacement.c
Labels: good first issue, hacktoberfest-accepted

#2 Improved File Readbility.
  SS/file allocation/file.c
Labels: bug, hacktoberfest-accepted

#3 Comments Added
  SS/cpu scheduling/Pg1cpu.c
Labels: documentation, hacktoberfest-accepted
